---
name: Test by compilation of exampleRoadmap

on:
  workflow_dispatch:
  push:
jobs:
  my_job:
    name: TestJob
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive-latex-base dvisvgm texlive-luatex texlive-latex-extra texlive-fonts-extra
      #- name: lookfor dvilualatex
      #  run: |
      #    sudo apt-get install apt-file
      #    sudo apt-file update
      #    apt-file search mathabx.sty
      - name: Compile exampleRoadmap
        run: |
          git checkout --orphan exampleoutput
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          dvilualatex -recorder exampleRoadmap.tex
          dvisvgm --no-fonts exampleRoadmap.dvi exampleRoadmap.svg
          git add -f exampleRoadmap.svg
          git commit -m "exampleRoadmap updated" exampleRoadmap.svg
          git push --force --set-upstream origin exampleoutput
          git checkout main
          git branch -D exampleoutput
