on:
  workflow_dispatch:
jobs:
  my_job:
    name: TestJob
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: list directory
        run: |
          git checkout --orphan exampleoutput
          git config core.editor code
          git config --global user.name "Dr. Bastian Ebeling"
          git config --global user.email 230051+Barry1@users.noreply.github.com
          latexmk -dvilua exampleRoadmap.tex
          dvisvgm --no-fonts exampleRoadmap.dvi exampleRoadmap.svg
          rm exampleRoadmap.dvi
          git add -f exampleRoadmap.svg
          git commit -m "exampleRoadmap updated" exampleRoadmap.svg
          git push --force --set-upstream origin exampleoutput
          git checkout main
          git branch -D exampleoutput
